name: Deploy dist branch

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checking Out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prepare Deploy
        id: prepare_deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          echo "--- Clone dist branch to directory. ---"
          git clone https://github.com/ittuann/qingshanasd.git dist-branch
          cd dist-branch
          MAIN_LATEST_HASH=$(git rev-parse --short=7 HEAD)
          git checkout dist
          cd ..

          echo "--- Clean old files: ---"
          echo "--- Delete all tracked files ---"
          git rm -rf . || echo "No tracked files to remove."
          echo "--- Delete all untracked files ---"
          git clean -fxd

          echo "--- Copy new files. ---"
          rsync -av --exclude=".git" dist-branch/ .
          git add .

          echo "--- Attempts to commit changes. If there are no changes the new commit will not be created. ---"
          git commit -s -m "Auto deployed dist branch - $MAIN_LATEST_HASH" || echo "No changes to commit."

          echo "--- Check if there has been a new commit. ---"
          LOCAL_HASH=$(git rev-parse HEAD)
          REMOTE_HASH=$(git rev-parse @{u})
          if [ "$LOCAL_HASH" != "$REMOTE_HASH" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Content has changed."
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "Content has not changed."
          fi

      - name: Push Commit
        if: steps.prepare_deploy.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
